// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package restdeeplinkmodule.proxies;

public class ExampleLinkEntity
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject exampleLinkEntityMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "RESTDeeplinkModule.ExampleLinkEntity";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		parameter1("parameter1"),
		parameter2("parameter2"),
		parameter3("parameter3");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ExampleLinkEntity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "RESTDeeplinkModule.ExampleLinkEntity"));
	}

	protected ExampleLinkEntity(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject exampleLinkEntityMendixObject)
	{
		if (exampleLinkEntityMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("RESTDeeplinkModule.ExampleLinkEntity", exampleLinkEntityMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a RESTDeeplinkModule.ExampleLinkEntity");

		this.exampleLinkEntityMendixObject = exampleLinkEntityMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'ExampleLinkEntity.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static restdeeplinkmodule.proxies.ExampleLinkEntity initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return restdeeplinkmodule.proxies.ExampleLinkEntity.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static restdeeplinkmodule.proxies.ExampleLinkEntity initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new restdeeplinkmodule.proxies.ExampleLinkEntity(context, mendixObject);
	}

	public static restdeeplinkmodule.proxies.ExampleLinkEntity load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return restdeeplinkmodule.proxies.ExampleLinkEntity.initialize(context, mendixObject);
	}

	public static java.util.List<restdeeplinkmodule.proxies.ExampleLinkEntity> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<restdeeplinkmodule.proxies.ExampleLinkEntity> result = new java.util.ArrayList<restdeeplinkmodule.proxies.ExampleLinkEntity>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//RESTDeeplinkModule.ExampleLinkEntity" + xpathConstraint))
			result.add(restdeeplinkmodule.proxies.ExampleLinkEntity.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of parameter1
	 */
	public final java.lang.String getparameter1()
	{
		return getparameter1(getContext());
	}

	/**
	 * @param context
	 * @return value of parameter1
	 */
	public final java.lang.String getparameter1(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.parameter1.toString());
	}

	/**
	 * Set value of parameter1
	 * @param parameter1
	 */
	public final void setparameter1(java.lang.String parameter1)
	{
		setparameter1(getContext(), parameter1);
	}

	/**
	 * Set value of parameter1
	 * @param context
	 * @param parameter1
	 */
	public final void setparameter1(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String parameter1)
	{
		getMendixObject().setValue(context, MemberNames.parameter1.toString(), parameter1);
	}

	/**
	 * @return value of parameter2
	 */
	public final java.lang.String getparameter2()
	{
		return getparameter2(getContext());
	}

	/**
	 * @param context
	 * @return value of parameter2
	 */
	public final java.lang.String getparameter2(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.parameter2.toString());
	}

	/**
	 * Set value of parameter2
	 * @param parameter2
	 */
	public final void setparameter2(java.lang.String parameter2)
	{
		setparameter2(getContext(), parameter2);
	}

	/**
	 * Set value of parameter2
	 * @param context
	 * @param parameter2
	 */
	public final void setparameter2(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String parameter2)
	{
		getMendixObject().setValue(context, MemberNames.parameter2.toString(), parameter2);
	}

	/**
	 * @return value of parameter3
	 */
	public final java.lang.String getparameter3()
	{
		return getparameter3(getContext());
	}

	/**
	 * @param context
	 * @return value of parameter3
	 */
	public final java.lang.String getparameter3(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.parameter3.toString());
	}

	/**
	 * Set value of parameter3
	 * @param parameter3
	 */
	public final void setparameter3(java.lang.String parameter3)
	{
		setparameter3(getContext(), parameter3);
	}

	/**
	 * Set value of parameter3
	 * @param context
	 * @param parameter3
	 */
	public final void setparameter3(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String parameter3)
	{
		getMendixObject().setValue(context, MemberNames.parameter3.toString(), parameter3);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return exampleLinkEntityMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final restdeeplinkmodule.proxies.ExampleLinkEntity that = (restdeeplinkmodule.proxies.ExampleLinkEntity) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "RESTDeeplinkModule.ExampleLinkEntity";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
