// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package restdeeplinkmodule.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the RESTDeeplinkModule module
	public static boolean aSU_ensureData(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			return (java.lang.Boolean)Core.execute(context, "RESTDeeplinkModule.ASU_ensureData", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static system.proxies.User authentication(IContext context, system.proxies.HttpRequest _httpRequest, system.proxies.HttpResponse _httpResponse)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("HttpRequest", _httpRequest == null ? null : _httpRequest.getMendixObject());
			params.put("HttpResponse", _httpResponse == null ? null : _httpResponse.getMendixObject());
			IMendixObject result = (IMendixObject)Core.execute(context, "RESTDeeplinkModule.Authentication", params);
			return result == null ? null : system.proxies.User.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static system.proxies.HttpResponse rEST_GetExamplePage(IContext context, java.lang.String _parameter2, java.lang.String _parameter3, java.lang.String _parameter1)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("parameter2", _parameter2);
			params.put("parameter3", _parameter3);
			params.put("parameter1", _parameter1);
			IMendixObject result = (IMendixObject)Core.execute(context, "RESTDeeplinkModule.REST_GetExamplePage", params);
			return result == null ? null : system.proxies.HttpResponse.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static system.proxies.HttpResponse status_303_SeeOther(IContext context, java.lang.String _location, system.proxies.HttpResponse _httpResponse)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Location", _location);
			params.put("HttpResponse", _httpResponse == null ? null : _httpResponse.getMendixObject());
			IMendixObject result = (IMendixObject)Core.execute(context, "RESTDeeplinkModule.Status_303_SeeOther", params);
			return result == null ? null : system.proxies.HttpResponse.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static system.proxies.HttpResponse status_404_NotFound(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			IMendixObject result = (IMendixObject)Core.execute(context, "RESTDeeplinkModule.Status_404_NotFound", params);
			return result == null ? null : system.proxies.HttpResponse.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
}